name: Examples CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    # don't run if any of these labels are present
    if: >
      !(
      contains(github.event.pull_request.labels.*.name, 'skip-ci') ||
      contains(github.event.pull_request.labels.*.name, 'skip-examples-ci')
      )
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.10' 
          - '1.12'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - name: Install dependencies (scripts)
        run: julia --project=examples/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run Soil Heat Column
        run: julia --project=examples/ examples/simulations/soil_heat_column.jl
      - name: Run Land Column
        run: julia --project=examples/ examples/simulations/land_column.jl
      - name: Run Snow Global
        run: julia --project=examples/ examples/simulations/snow_global.jl
      - name: Run Vegetation Global
        run: julia --project=examples/ examples/simulations/vegetation_global.jl
      # - name: Run SpeedyWeather Wet coupling
      #   run: julia --project=examples/ examples/simulations/speedy_wet_land.jl
      
        